var ASTEROID_POINTS = 12;
var ASTEROID_HP = 4;
var ASTEROID_VELOCITY = 1;

var SHIP_ACCEL = 0.1;
var SHIP_TURN = Math.PI*2 / 100;
var SHIP_SLOW = 0.02;

var BULLET_SPEED = 4;
var BULLET_DISTANCE = 800;
var BULLET_LENGTH = 4;